export let dataSources =[
{
    "Id": 1,
    "HouseID": "STSTNR220905096A",
    "Customer": "HAVICO",
    "Percent":50,
    "FeeType": "O/F",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 2,
    "HouseID": "STSTNR220905096A",
    "Customer": "HAVICO",
    "Percent":50,
    "FeeType": "SI",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 3,
    "HouseID": "STSTNR220905096B",
    "Customer": "NTF",
    "Percent":50,
    "FeeType": "UA",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 4,
    "HouseID": "STSTNR220905096B",
    "Customer": "NTF",
    "Percent":50,
    "FeeType": "NU",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},{
    "Id": 5,
    "HouseID": "STSTNR220905096B",
    "Customer": "HAVICO",
    "Percent":50,
    "FeeType": "O/F",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 6,
    "HouseID": "STSTNR220905096B",
    "Customer": "HAVICO",
    "Percent":50,
    "FeeType": "AA",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 7,
    "HouseID": "STSTNR220905096A",
    "Customer": "NTF",
    "Percent":50,
    "FeeType": "O/F",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
},
{
    "Id": 8,
    "HouseID": "STSTNR220905096A",
    "Customer": "NTF",
    "Percent":50,
    "FeeType": "O/F",
    "Money": 1000,
    "VAT": 8,
    "MoneyVAT": 1000,
    "ExportVATContract": true,
    "DateExportVATContract": "12/05/2022",
    "importMisa": false,
    "PaymentStatus" : true,
    "FeeNote": "phí của dịch vụ",
    "FeeDescription":"Phí của dịch vụ",
    "ConfirmStatus" : true
}
]